drop table if exists stock_analysis.STOCK_DAILY_WIDE_DIGEST;
create table if not exists stock_analysis.STOCK_DAILY_WIDE_DIGEST (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE VARCHAR(16),
    PARTITION_DATE VARCHAR(16),
    EXT_INFO MEDIUMTEXT,
    GMT_CREATE DATETIME,
    GMT_MODIFIED DATETIME
);